# Generated by Django 3.0.5 on 2020-05-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('electric', models.IntegerField()),
                ('water', models.IntegerField()),
                ('gas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('electric', models.IntegerField()),
                ('water', models.IntegerField()),
                ('gas', models.IntegerField()),
            ],
        ),
    ]
