# Generated by Django 3.0.5 on 2020-05-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0003_auto_20200504_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='meas',
            new_name='elec',
        ),
        migrations.RemoveField(
            model_name='all',
            name='util',
        ),
        migrations.AddField(
            model_name='all',
            name='gas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='all',
            name='water',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
